id = "jasm-lang"
name = "JASM Assembly Language"
version = "0.0.1"
schema_version = 1
authors = ["Josiah Bergen <hello@jojobinx.com>"]
description = "JASM language support for the Zed code editor."
repository = "https://github.com/josiahbergen/zed-jasm"

[grammars.jasm]
repository = "https://github.com/josiahbergen/zed-jasm"
rev = "5a87f0ca1648848c7751e635a8d2309272b51b0a" # sha of the most recent commit to the grammar branch
