id = "jasm-lang"
name = "JASM Assembly Language"
version = "0.0.1"
schema_version = 1
authors = ["Josiah Bergen <hello@jojobinx.com>"]
description = "JASM language support for the Zed code editor."
repository = "https://github.com/josiahbergen/zed-jasm"

[grammars.jasm]
repository = "https://github.com/josiahbergen/zed-jasm"
rev = "e37eedbe77e01ea805a7aea984919bf18800f78b" # sha of the most recent commit to the grammar branch
